import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seeding...');

  // 1. Clean existing database records
  await prisma.internalNote.deleteMany({});
  await prisma.requestEvent.deleteMany({});
  await prisma.aIClassification.deleteMany({});
  await prisma.customerRequest.deleteMany({});
  await prisma.user.deleteMany({});

  console.log('🧹 Cleaned existing database records.');

  // 2. Hash passwords
  const saltRounds = 12;
  const adminPasswordHash = await bcrypt.hash('Admin123!', saltRounds);
  const agentPasswordHash = await bcrypt.hash('Agent123!', saltRounds);

  // 3. Create Users
  const admin = await prisma.user.create({
    data: {
      email: 'admin@cognifyr.co',
      passwordHash: adminPasswordHash,
      name: 'Admin User',
      role: 'ADMIN'
    }
  });

  const agent = await prisma.user.create({
    data: {
      email: 'agent@cognifyr.co',
      passwordHash: agentPasswordHash,
      name: 'Agent User',
      role: 'AGENT'
    }
  });

  console.log(`👤 Created Admin: ${admin.email}`);
  console.log(`👤 Created Agent: ${agent.email}`);

  // 4. Create 10 Sample Customer Requests
  
  // Request 1: Brand new request
  const req1 = await prisma.customerRequest.create({
    data: {
      customerName: 'Alice Green',
      customerEmail: 'alice@example.com',
      message: 'Hello, I cannot find the checkout button on your pricing page. Can you please guide me?',
      sourceChannel: 'WEBSITE_FORM',
      status: 'NEW',
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW', actorId: admin.id }
        ]
      }
    }
  });

  // Request 2: Queued request
  const req2 = await prisma.customerRequest.create({
    data: {
      customerName: 'Robert Vance',
      customerPhone: '+15550199',
      message: 'Urgent: My integration is throwing 500 errors since this morning. Please help asap.',
      sourceChannel: 'WEBHOOK_WHATSAPP',
      status: 'QUEUED',
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' }
        ]
      }
    }
  });

  // Request 3: Request currently classifying
  const req3 = await prisma.customerRequest.create({
    data: {
      customerName: 'Elena Rostova',
      customerEmail: 'elena@gmail.com',
      message: 'I would like to request a demo of the enterprise dashboard for my team of 50.',
      sourceChannel: 'WEBSITE_FORM',
      status: 'CLASSIFYING',
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' },
          { eventType: 'status_changed', oldValue: 'QUEUED', newValue: 'CLASSIFYING' }
        ]
      }
    }
  });

  // Request 4: Classified as High Priority Support
  const req4 = await prisma.customerRequest.create({
    data: {
      customerName: 'John Doe',
      customerEmail: 'john.doe@techcorp.com',
      message: 'My card was charged twice for the monthly subscription. Please issue a refund for the second transaction.',
      sourceChannel: 'API',
      status: 'CLASSIFIED',
      categorySnapshot: 'support',
      prioritySnapshot: 'HIGH',
      classifications: {
        create: [
          {
            provider: 'mock',
            category: 'support',
            priority: 'HIGH',
            summary: 'Double charge on subscription card requiring refund.',
            confidence: 0.94,
            reason: 'Contains keywords "charged twice", "refund" indicating billing Support issue.',
            rawOutput: { note: 'Generated by seed' }
          }
        ]
      },
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' },
          { eventType: 'status_changed', oldValue: 'QUEUED', newValue: 'CLASSIFYING' },
          { eventType: 'classified', newValue: 'support/HIGH' }
        ]
      }
    }
  });

  // Request 5: Classified and currently IN_PROGRESS
  const req5 = await prisma.customerRequest.create({
    data: {
      customerName: 'Marcus Aurelius',
      customerEmail: 'marcus@philosophy.org',
      message: 'Help, I cannot login to my account. It says password incorrect but resetting password sends no email.',
      sourceChannel: 'WEBSITE_FORM',
      status: 'IN_PROGRESS',
      categorySnapshot: 'support',
      prioritySnapshot: 'HIGH',
      classifications: {
        create: [
          {
            provider: 'mock',
            category: 'support',
            priority: 'HIGH',
            summary: 'Unable to log in and password reset email not received.',
            confidence: 0.91,
            reason: 'Identified "cannot login", "incorrect password", "resetting password" keywords.',
            rawOutput: { note: 'Generated by seed' }
          }
        ]
      },
      notes: {
        create: [
          {
            authorId: agent.id,
            body: 'Investigated backend logs. Reset email service had a brief delay. Triggered password reset manual email to customer.'
          }
        ]
      },
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' },
          { eventType: 'status_changed', oldValue: 'QUEUED', newValue: 'CLASSIFYING' },
          { eventType: 'classified', newValue: 'support/HIGH' },
          { eventType: 'status_changed', oldValue: 'CLASSIFIED', newValue: 'IN_PROGRESS', actorId: agent.id },
          { eventType: 'note_added', actorId: agent.id }
        ]
      }
    }
  });

  // Request 6: Fully Resolved Request
  const req6 = await prisma.customerRequest.create({
    data: {
      customerName: 'Sarah Jenkins',
      customerEmail: 'sarah@designhub.co',
      message: 'Hey, do you support custom font uploads in the editor? We need this for our corporate design team.',
      sourceChannel: 'API',
      status: 'RESOLVED',
      categorySnapshot: 'sales',
      prioritySnapshot: 'MEDIUM',
      classifications: {
        create: [
          {
            provider: 'mock',
            category: 'sales',
            priority: 'MEDIUM',
            summary: 'Pre-sales inquiry regarding custom font upload support.',
            confidence: 0.85,
            reason: 'Contains feature interest "custom font uploads" mapping to Sales/Feature inquiries.',
            rawOutput: { note: 'Generated by seed' }
          }
        ]
      },
      notes: {
        create: [
          {
            authorId: agent.id,
            body: 'Emailed user explaining our custom assets guide and that Enterprise plan supports custom fonts uploads.'
          }
        ]
      },
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' },
          { eventType: 'status_changed', oldValue: 'QUEUED', newValue: 'CLASSIFYING' },
          { eventType: 'classified', newValue: 'sales/MEDIUM' },
          { eventType: 'status_changed', oldValue: 'CLASSIFIED', newValue: 'IN_PROGRESS', actorId: agent.id },
          { eventType: 'note_added', actorId: agent.id },
          { eventType: 'status_changed', oldValue: 'IN_PROGRESS', newValue: 'RESOLVED', actorId: agent.id }
        ]
      }
    }
  });

  // Request 7: Marked as SPAM
  const req7 = await prisma.customerRequest.create({
    data: {
      customerName: 'Casino Broker',
      customerPhone: '+919999999999',
      message: 'GET RICH FAST! Click here http://casino-win-jackpot.xyz to claim free $100 bonus cash immediately!!!',
      sourceChannel: 'WEBHOOK_WHATSAPP',
      status: 'SPAM',
      categorySnapshot: 'spam',
      prioritySnapshot: 'LOW',
      classifications: {
        create: [
          {
            provider: 'mock',
            category: 'spam',
            priority: 'LOW',
            summary: 'Spam Casino promotion and link injection.',
            confidence: 0.99,
            reason: 'Contains keywords indicating standard promotional spam: "GET RICH FAST", "http://", "free $100".',
            rawOutput: { note: 'Generated by seed' }
          }
        ]
      },
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' },
          { eventType: 'status_changed', oldValue: 'QUEUED', newValue: 'CLASSIFYING' },
          { eventType: 'classified', newValue: 'spam/LOW' },
          { eventType: 'status_changed', oldValue: 'CLASSIFIED', newValue: 'SPAM', actorId: admin.id }
        ]
      }
    }
  });

  // Request 8: Failed Classification
  const req8 = await prisma.customerRequest.create({
    data: {
      customerName: 'Anonymous Sender',
      customerEmail: 'anon@secret.com',
      message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.',
      sourceChannel: 'WEBHOOK_EMAIL',
      status: 'FAILED',
      classifications: {
        create: [
          {
            provider: 'mock',
            errorState: 'Failed to extract JSON format block from provider response.',
            retryCount: 3
          }
        ]
      },
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' },
          { eventType: 'status_changed', oldValue: 'QUEUED', newValue: 'CLASSIFYING' },
          { eventType: 'classification_failed', newValue: 'FAILED' }
        ]
      }
    }
  });

  // Request 9: Classified Sales Request
  const req9 = await prisma.customerRequest.create({
    data: {
      customerName: 'Clara Oswald',
      customerEmail: 'clara.oswald@tardis.org',
      message: 'Hello, our agency is looking to transition from Zendesk to Cognifyr. What is your pricing structure for 15 seats?',
      sourceChannel: 'API',
      status: 'CLASSIFIED',
      categorySnapshot: 'sales',
      prioritySnapshot: 'MEDIUM',
      classifications: {
        create: [
          {
            provider: 'mock',
            category: 'sales',
            priority: 'MEDIUM',
            summary: 'Zendesk migration inquiry and pricing for 15 seats.',
            confidence: 0.90,
            reason: 'Identified pre-sales intent, migration request, and seating quote keywords.',
            rawOutput: { note: 'Generated by seed' }
          }
        ]
      },
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' },
          { eventType: 'status_changed', oldValue: 'QUEUED', newValue: 'CLASSIFYING' },
          { eventType: 'classified', newValue: 'sales/MEDIUM' }
        ]
      }
    }
  });

  // Request 10: In Progress Urgent Triage
  const req10 = await prisma.customerRequest.create({
    data: {
      customerName: 'Tony Stark',
      customerPhone: '+11234567890',
      message: 'EMERGENCY: ARC reactor cooling systems are failing. Error code 0x7A. System shutting down in 30 minutes!',
      sourceChannel: 'WEBHOOK_WHATSAPP',
      status: 'IN_PROGRESS',
      categorySnapshot: 'urgent',
      prioritySnapshot: 'HIGH',
      classifications: {
        create: [
          {
            provider: 'mock',
            category: 'urgent',
            priority: 'HIGH',
            summary: 'Reactor cooling failure error code 0x7A.',
            confidence: 0.97,
            reason: 'Detected emergency indicator "EMERGENCY", "shutting down", "failing". Set to HIGH priority.',
            rawOutput: { note: 'Generated by seed' }
          }
        ]
      },
      notes: {
        create: [
          {
            authorId: admin.id,
            body: 'Spoke with Pepper. Advised rebooting backup cooling rods manually.'
          }
        ]
      },
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' },
          { eventType: 'status_changed', oldValue: 'QUEUED', newValue: 'CLASSIFYING' },
          { eventType: 'classified', newValue: 'urgent/HIGH' },
          { eventType: 'status_changed', oldValue: 'CLASSIFIED', newValue: 'IN_PROGRESS', actorId: admin.id },
          { eventType: 'note_added', actorId: admin.id }
        ]
      }
    }
  });

  console.log('🎉 Database seeding completed successfully! Created 10 sample requests.');
}

main()
  .catch((e) => {
    console.error('🚨 Error occurred during database seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
