import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting minimal database seeding...');

  // 1. Clean existing database records
  await prisma.internalNote.deleteMany({});
  await prisma.requestEvent.deleteMany({});
  await prisma.aIClassification.deleteMany({});
  await prisma.customerRequest.deleteMany({});
  await prisma.user.deleteMany({});

  console.log('🧹 Cleaned existing database records.');

  // 2. Hash passwords
  const saltRounds = 12;
  const adminPasswordHash = await bcrypt.hash('admin123', saltRounds);
  const agentPasswordHash = await bcrypt.hash('Agent123!', saltRounds);

  // 3. Create core Admin and Agent operator users
  const admin = await prisma.user.create({
    data: {
      email: 'admin@123.com',
      passwordHash: adminPasswordHash,
      name: 'Admin User',
      role: 'ADMIN'
    }
  });

  const agent = await prisma.user.create({
    data: {
      email: 'agent@senseai.co',
      passwordHash: agentPasswordHash,
      name: 'Agent User',
      role: 'AGENT'
    }
  });

  console.log(`👤 Created Admin: ${admin.email}`);
  console.log(`👤 Created Agent: ${agent.email}`);

  // 4. Create 5 Minimal, Clean Customer Requests for Testing

  // Case 1: Fresh ticket ready for AI classification
  const req1 = await prisma.customerRequest.create({
    data: {
      customerName: 'Sarah Carter',
      customerEmail: 'sarah.carter@gmail.com',
      message: 'I noticed two duplicate charges of $49.00 on my bank statement from your service this morning. I only subscribed to one plan. Please refund the duplicate transaction immediately!',
      sourceChannel: 'WEBSITE_FORM',
      status: 'NEW',
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW', actorId: admin.id }
        ]
      }
    }
  });

  // Case 2: Enterprise pre-sales inquiry in the queue
  const req2 = await prisma.customerRequest.create({
    data: {
      customerName: 'David Miller',
      customerEmail: 'david.miller@techcorp.com',
      message: 'Hi, our procurement team is looking to onboard 150 employees onto your workflow platform. Do you offer bulk licensing discounts, and can we schedule a demo of your SSO/SAML integrations this week?',
      sourceChannel: 'API',
      status: 'QUEUED',
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' }
        ]
      }
    }
  });

  // Case 3: Emergency Outage ticket in progress of classification
  const req3 = await prisma.customerRequest.create({
    data: {
      customerName: 'James Henderson',
      customerPhone: '+15558392',
      message: 'EMERGENCY: Our production API integration is throwing continuous 502 Bad Gateway errors. All customer checkouts are blocked. We need immediate assistance as this is causing significant revenue loss!',
      sourceChannel: 'WEBHOOK_WHATSAPP',
      status: 'CLASSIFYING',
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' },
          { eventType: 'status_changed', oldValue: 'QUEUED', newValue: 'CLASSIFYING' }
        ]
      }
    }
  });

  // Case 4: Ticket pre-classified as spam
  const req4 = await prisma.customerRequest.create({
    data: {
      customerName: 'Spam Bot 3000',
      message: 'CONGRATULATIONS!!! You have been selected as our grand lucky prize winner of the day! Click this link http://get-free-cash-today.net to claim your $5,000 Amazon gift card voucher instantly! No credit card required!',
      sourceChannel: 'WEBHOOK_WHATSAPP',
      status: 'SPAM',
      categorySnapshot: 'spam',
      prioritySnapshot: 'LOW',
      classifications: {
        create: [
          {
            provider: 'mock',
            category: 'spam',
            priority: 'LOW',
            summary: 'Spam lucky winner sweepstakes advertising link.',
            confidence: 0.99,
            reason: 'Contains typical spam trigger keywords "LUCKY WINNER" and "http://"',
            rawOutput: { note: 'Generated by seed' }
          }
        ]
      },
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' },
          { eventType: 'status_changed', oldValue: 'QUEUED', newValue: 'CLASSIFYING' },
          { eventType: 'classified', newValue: 'spam/LOW' },
          { eventType: 'status_changed', oldValue: 'CLASSIFIED', newValue: 'SPAM', actorId: admin.id }
        ]
      }
    }
  });

  // Case 5: Classification failed, ideal for manual retry button testing
  const req5 = await prisma.customerRequest.create({
    data: {
      customerName: 'Emily Watson',
      customerEmail: 'ux-fan@gmail.com',
      message: 'Hello, I am really enjoying using the dashboard! Just wanted to ask if you have any plans to release a mobile application or custom dashboard profile layout editor soon?',
      sourceChannel: 'WEBHOOK_EMAIL',
      status: 'FAILED',
      classifications: {
        create: [
          {
            provider: 'mock',
            errorState: 'Failed to extract JSON format block from provider response.',
            retryCount: 3
          }
        ]
      },
      events: {
        create: [
          { eventType: 'created', newValue: 'NEW' },
          { eventType: 'status_changed', oldValue: 'NEW', newValue: 'QUEUED' },
          { eventType: 'status_changed', oldValue: 'QUEUED', newValue: 'CLASSIFYING' },
          { eventType: 'classification_failed', newValue: 'FAILED' }
        ]
      }
    }
  });

  console.log('🎉 Minimal database seeding completed successfully! Created 5 clean test requests.');
}

main()
  .catch((e) => {
    console.error('🚨 Error occurred during minimal seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
